## Array

### In array, we need to have all the values of same type

In [4]:
from array import *
vals=array('i',[5,6,7])


In [5]:
print(vals)

array('i', [5, 6, 7])


In [7]:
print(vals.buffer_info())

(139958047318464, 3)


In [9]:
print(vals.typecode)

i


In [11]:
vals.reverse()
print(vals)

array('i', [5, 6, 7])


In [12]:
vals=array('i',[5,6,7])
vals.reverse()
print(vals)

array('i', [7, 6, 5])


In [13]:
print(vals[0])

7


In [17]:
for i in range(len(vals)):
    print(vals[i])

7
6
5


In [18]:
for e in vals:
    print(e)

7
6
5


In [26]:
newarr=array(vals.typecode, (a*a*a for a in vals))
print(newarr)
print(len(newarr))

array('i', [343, 216, 125])
3


In [25]:
i=0
while i<len(newarr):
    print(newarr[i])
    i=i+1

343
216
125


In [33]:
arr=array('i',[])
n=int(input('Enter the length of array'))
for i in range(n):
    x=int(input('Enter the next value'))
    arr.append(x)
print(arr)

Enter the length of array4
Enter the next value12
Enter the next value13
Enter the next value14
Enter the next value15
array('i', [12, 13, 14, 15])


In [37]:
k=0
val=int(input('Enter the value to be checked'))
for e in arr:
    if val==e:
        print(k)
        break
    k+=1
        
print(arr.index(val))  

Enter the value to be checked12
0
0


In [40]:
from numpy import *
arr=array([1,2])
print(arr)

[1 2]


### Ways of creating arrays in numpy

In [43]:
from numpy import *
arr=array([1,2,3,4.2,5])
print(arr)
print(arr.dtype)

[1.  2.  3.  4.2 5. ]
float64


In [45]:
# It will divide into 21 parts
arr=linspace(0,20,21)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20.]


In [46]:
arr=linspace(0,20)
print(arr)

[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]


In [47]:
# The last argument is step
arr=arange(1,20,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [48]:
arr=logspace(1,40,5)
print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [51]:
arr=zeros(6)
arr1=ones(5)
arr2=ones(5,int)
print(arr)
print(arr1)
print(arr2)

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 1 1 1 1]
