In [4]:
from numpy import *
arr=array([1,2,3,4,5])
for i in range(len(arr)):
    arr[i]=arr[i]+5
print(arr)

[ 6  7  8  9 10]


In [5]:
arr=array([1,2,3,4,5])
arr=arr+5
print(arr)

[ 6  7  8  9 10]


### Vectorized Opertaions

In [6]:
arr1=array([1,2,3,4])
arr2=array([5,6,7,8])
arr=arr1+arr2
print(arr)

[ 6  8 10 12]


In [8]:
arr1=array([0,30,45,60,90])
print(sin(arr1))
print(sqrt(arr1))
print(log(arr1))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[0.         5.47722558 6.70820393 7.74596669 9.48683298]
[      -inf 3.40119738 3.80666249 4.09434456 4.49980967]


/snap/jupyter/6/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


In [10]:
print(sum(arr1))
print(min(arr1))
print(max(arr1))

225
0
90


In [12]:
arr1=array([1,2])
arr2=array([3,4])
arr=concatenate([arr1,arr2])
print(arr)

[1 2 3 4]


In [14]:
# Aliasing
arr1=array([1,2,3])
arr2=arr1
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[1 2 3]
[1 2 3]
140319650615904
140319650615904


In [18]:
# Shallow copy
arr1=array([1,2,3])
arr2=arr1.view()
arr1[1]=3
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))


[1 3 3]
[1 3 3]
140319650616864
140319650617264


In [19]:
# Deep copy
arr1=array([1,2,3])
arr2=arr1.copy()
arr1[1]=3
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[1 3 3]
[1 2 3]
140319650616624
140319650617744


In [29]:
# Playing with array
arr1=array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
         ])
print(arr1)
print(arr1.dtype)
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
arr2=arr1.flatten()
print(arr2)
arr3=arr2.reshape(3,3)
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
2
(3, 3)
9
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
arr1=array([
    [1,2,3,4,5,6],
    [7,8,9,10,11,12]
])
arr2=arr1.reshape(2,2,3)
print(arr2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [37]:
m=matrix('1 2 3; 4 5 6 ;7 8 9')
print(diagonal(m))
print(m.min())
print(m.max())

[1 5 9]
1
9


In [40]:
# Multiplication of matrices
m1= matrix('1 2 3; 4 5 6 ;7 8 9')
m2= matrix('1 1 3; 4 5 5 ;9 8 9')
print(m1)
print(m2)
m3=m1+m2
m4=m1*m2
print(m3)
print(m4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 3]
 [4 5 5]
 [9 8 9]]
[[ 2  3  6]
 [ 8 10 11]
 [16 16 18]]
[[ 36  35  40]
 [ 78  77  91]
 [120 119 142]]


### Functions in python

In [1]:
def greet():
    print('hello')
    print("Good Morning")
greet()

hello
Good Morning


In [2]:
def add(a,b):
    return a+b
c=add(4,5)
print(c)

9


In [4]:
def add_sub(a,b):
    c=a+b
    d=a-b
    return c,d
result1, result2=add_sub(6,2)
print(result1, result2)

8 4
