# Numpy
## NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with python

In [1]:
import numpy as np

numpy.ndarray

array([1, 2, 3, 4, 5])

(5,)

In [33]:
## multidimensional array
my_lst1=[1,2,3,4,5]
my_lst2=[6,7,8,9,19]
my_lst3=[11,12,13,14,15]
arr=np.array([my_lst1,my_lst2,my_lst3])

In [34]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 19],
       [11, 12, 13, 14, 15]])

In [35]:
arr.shape

(3, 5)

In [38]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [42]:
arr=np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [15]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [19, 11, 12],
       [13, 14, 15]])

In [43]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [45]:
arr[3:]=100
arr

array([  0,   2,   4, 100, 100])

## Indexing

In [48]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [49]:
arr[3]

4

In [53]:
val=2
arr[arr<2]

array([1])

In [55]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [56]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
np.random.rand(4,4)

array([[4.23741276e-01, 6.08132807e-01, 4.77686806e-01, 2.86058946e-04],
       [9.03216873e-01, 5.06559276e-02, 8.06934958e-01, 9.04574178e-01],
       [5.52301783e-01, 9.74877111e-01, 3.80358543e-01, 1.63406568e-02],
       [5.03616606e-01, 9.21677822e-01, 4.40677266e-01, 1.87787817e-01]])

In [62]:
arr_ex=np.random.randn(4,4)

In [63]:
arr_ex

array([[-1.53565651, -0.98415077,  1.63610969,  1.08214597],
       [ 0.85322978, -0.33898884, -0.18004893,  0.24141316],
       [-0.50832743,  0.63058794, -1.26592068, -0.04851313],
       [-0.48473967, -1.05919425,  0.647724  , -0.88504153]])

In [64]:
np.random.random_sample((1,5))

array([[6.02099657e-04, 2.16430292e-01, 7.19950182e-01, 9.78183077e-01,
        3.71310197e-01]])