In [1]:
import numpy as np


In [2]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.shape

(5,)

In [6]:
my_lst1=[1,2,3]
my_lst2=[4,5,6]
my_lst3=[7,8,9]
arr=np.array([my_lst1,my_lst2,my_lst3])

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr.shape

(3, 3)

In [9]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [10]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

In [11]:
arr[1]

2

In [12]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr=np.array([[1,2,3],[3,3,3]])

In [21]:
arr

array([[1, 2, 3],
       [3, 3, 3]])

In [22]:
arr[:,:]

array([[1, 2, 3],
       [3, 3, 3]])

In [23]:
arr[1:,1:]

array([[3, 3]])

In [27]:
arr=np.arange(0,10,2)

In [28]:
arr

array([0, 2, 4, 6, 8])

In [29]:
np.linspace(1,2,50)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [32]:
#Copy function and broadcasting
arr[3:]=1

In [31]:
arr

array([0, 2, 4, 1, 1])

In [33]:
arr1=arr
arr1[2:]=500

In [34]:
arr1

array([  0,   2, 500, 500, 500])

In [35]:
arr

array([  0,   2, 500, 500, 500])

In [36]:
arr1=arr.copy()
print(arr)
arr1[1:]=0
print(arr)
print(arr1)

[  0   2 500 500 500]
[  0   2 500 500 500]
[0 0 0 0 0]


In [41]:
val=500
arr[arr<val]

array([0, 2])

In [42]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
arr1=np.arange(0,10).reshape(2,5)
arr2=np.arange(10,20).reshape(2,5)

In [44]:
arr1.shape

(2, 5)

In [45]:
arr2.shape

(2, 5)

In [46]:
arr=arr1*arr2

In [47]:
arr

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

In [49]:
np.ones(2,int)

array([1, 1])

In [50]:
np.zeros(5,float)

array([0., 0., 0., 0., 0.])

In [51]:
np.random.rand(2,2)

array([[0.13924548, 0.79652817],
       [0.96057138, 0.04909574]])

In [60]:
arr_ex=np.random.randn(3,3)

In [61]:
arr_ex

array([[-0.47173621,  0.52845936, -0.27276842],
       [-0.40053634,  0.6555271 , -0.73356681],
       [ 0.1651811 ,  0.16768476,  0.61559076]])

In [64]:
np.random.randint(0,100,9).reshape(3,3)

array([[35, 85, 10],
       [34, 50, 17],
       [81, 32, 63]])