In [7]:
person={'name':'jenn','age':23}
sentence="My name is {0[name]} and I am {0[age]} years old".format(person)
print(sentence)

My name is jenn and I am 23 years old


# Numpy

In [9]:
import numpy as np
a=np.zeros(3)
type(a)

numpy.ndarray

In [10]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
z.shape

(10,)

In [13]:
a=np.empty(3)
a

array([0., 0., 0.])

In [21]:
z=np.linspace(2,2.01,5)
print(z)

[2.     2.0025 2.005  2.0075 2.01  ]


In [22]:
z=np.array([10,20])
z

array([10, 20])

In [24]:
a_list=[[1,2,3],[4,5,6]]
z=np.array(a_list)
z.shape

(2, 3)

In [25]:
np.random.seed(0)
z1=np.random.randint(10,size=6)
z1

array([5, 0, 3, 3, 7, 9])

In [27]:
z1[4]

7